service: videolyzer

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  profile: ${file(../config.${self:provider.stage}.json):videolyzer.profile}
  stage: dev
  region: us-east-1

functions:
  start_processing_video:
    handler: handler.start_processing_video
    events:
      - s3:
          bucket: ${file(../config.${self:provider.stage}.json):videolyzer.videos_bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: mp4

